Support old middleware interface
Fixes error:

    ArgumentError: wrong number of arguments (3 for 4)

on middleware calls, and

    NoMethodError: undefined method `redis_pool' for Sidekiq:Module

on tests `after` block.

The new middleware interface has been introduced in Sidekiq 3.0, see
https://github.com/mperham/sidekiq/blob/v3.1.1/3.0-Upgrade.md